import { StyleSheet } from "react-native";

const createStyles = (dimensions) => {
  return StyleSheet.create({
    bgImage: {
      flex: 1,
      resizeMode: "cover",
      width: dimensions.width,
      height: dimensions.height + 142,
    },
    scrollViewContent: {
      flexGrow: 1,
      justifyContent: "flex-end",
      alignItems: "center",
      width: dimensions.width,
      height: dimensions.height,
    },
    form: {
      alignItems: "center",
      backgroundColor: "#FFFFFF",
      paddingHorizontal: 16,
      borderTopLeftRadius: 25,
      borderTopRightRadius: 25,
      paddingBottom: 45,
      position: "relative",
    },
    avatar: {
      position: "absolute",
      top: -60,
      left: "auto",
      width: 120,
      height: 120,
      zIndex: 1,
      borderRadius: 16,
      backgroundColor: "#F6F6F6",
    },
    icon: {
      position: "absolute",
      right: -13,
      bottom: 14,
      width: 25,
      height: 25,
    },
    title: {
      marginTop: 92,
      marginBottom: 32,
      fontFamily: "Roboto-Medium",
      fontSize: 30,
      fontWeight: 500,
      lineHeight: 35,
      letterSpacing: 0.01,
      color: "#212121",
    },
    input: {
      width: "100%",
      minHeight: 50,
      marginBottom: 16,
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 15,
      fontFamily: "Roboto-Regular",
      fontSize: 16,
      lineHeight: 19,
      borderWidth: 1,
      borderRadius: 8,
      borderColor: "#E8E8E8",
      backgroundColor: "#F6F6F6",
      color: "#212121",
    },
    inputFocused: {
      borderColor: "#FF6C00",
      backgroundColor: "#ffffff",
    },
    inputContainer: {
      position: "relative",
      width: "100%",
    },
    showPassword: {
      color: "#1B4371",
      fontFamily: "Roboto-Regular",
      fontSize: 16,
      lineHeight: 19,
    },
    showPasswordBtn: {
      position: "absolute",
      bottom: 16,
      right: 16,
      paddingTop: 16,
      paddingBottom: 15,
    },
    btn: {
      marginTop: 27,
      width: "100%",
      borderRadius: 100,
      marginBottom: 16,
      paddingHorizontal: 16,
      paddingVertical: 16,
      backgroundColor: "#FF6C00",
      borderWidth: 1,
      borderColor: "transparent",
    },
    btnText: {
      textAlign: "center",
      fontFamily: "Roboto-Regular",
      fontSize: 16,
      lineHeight: 19,
      color: "#ffffff",
    },
    loginText: {
      color: "#1B4371",
      padding: 16,
      lineHeight: 19,
      fontFamily: "Roboto-Regular",
    },
    underlinedText: {
      textDecorationLine: "underline",
      padding: 16,
    },
  });
};

export default createStyles;
